#!/usr/bin/env python3
"""Emit components/storage/ext_defaults_embedded.c from bundled /ext defaults.

Includes:
  - assets/ext_defaults/** (dolphin, asset_packs, …)
  - applications/main/{subghz,infrared,nfc}/resources/<app>/** → paths subghz/…, infrared/…, nfc/…

On ESP32, storage_ext_try_seed_defaults() writes any missing paths to the SD root (0:/…),
matching Flipper/Momentum layout (/ext maps to volume root, not a physical \"ext\" folder).
"""

from __future__ import annotations

import sys
from pathlib import Path


def c_escape(b: bytes) -> str:
    parts: list[str] = []
    for x in b:
        parts.append(f"0x{x:02x}")
    return ", ".join(parts)


def collect_files(root: Path) -> dict[str, Path]:
    by_rel: dict[str, Path] = {}

    src_root = root / "assets" / "ext_defaults"
    if src_root.is_dir():
        for path in sorted(src_root.rglob("*")):
            if path.is_file():
                rel = path.relative_to(src_root).as_posix()
                by_rel[rel] = path

    extra_trees: list[tuple[Path, str]] = [
        (root / "applications" / "main" / "subghz" / "resources" / "subghz", "subghz"),
        (root / "applications" / "main" / "infrared" / "resources" / "infrared", "infrared"),
        (root / "applications" / "main" / "nfc" / "resources" / "nfc", "nfc"),
    ]
    for base, prefix in extra_trees:
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_file():
                rel = prefix + "/" + path.relative_to(base).as_posix()
                by_rel[rel] = path

    return by_rel


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    out_c = root / "components" / "storage" / "ext_defaults_embedded.c"

    by_rel = collect_files(root)
    if not by_rel:
        print("No embedded default files found", file=sys.stderr)
        return 1

    files = sorted(by_rel.items(), key=lambda x: x[0])

    lines: list[str] = [
        "/* Generated by tools/fam/embed_ext_defaults.py — do not edit. */",
        '#include "ext_defaults_embedded.h"',
        "#include <stddef.h>",
        "",
    ]
    for i, (rel, path) in enumerate(files):
        data = path.read_bytes()
        sym = f"ext_defaults_blob_{i}"
        lines.append(f"static const uint8_t {sym}[] = {{ {c_escape(data)} }};")
        lines.append("")
    lines.append("const ExtDefaultEmbeddedFile ext_defaults_embedded_files[] = {")
    for i, (rel, path) in enumerate(files):
        sym = f"ext_defaults_blob_{i}"
        lines.append(f'    {{ "{rel}", {sym}, sizeof({sym}) }},')
    lines.append("};")
    lines.append("")
    lines.append(f"const size_t ext_defaults_embedded_files_count = {len(files)};")
    lines.append("")
    out_c.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(files)} files -> {out_c}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
